### ISSUE TITLE
Ngram word count

### ISSUE THREAD

**Issue by manojsingh101** [IBMStreams/streamsx.nlp#16]
Ngrams operator produces char sequence instead of words/terms. For example for ngrams size=2u and for input text="countries of the world", it produces "co", "ou", etc, instead of ngrams words like "countries of".
NgramBasic on the other hand work as expected and produces words. but the count functionality is not available in this operator.

So either Ngrams operator can be changed to produce words or NgramBasic can be extended to produce counts.

**Comment by markheger** [comment]
I propose to add a new custom output function to the NgramBasic operator to return a map of n-gram terms and the corresponding count.

    stream<rstring text, map<rstring, uint32> ngramMap> A = NgramBasic() {
       param
          documentAttribute: "text";
          size: 3u;
          minSize: 1u;
       output A : ngramMap = NgramCount();
    }

Please approve if this meets your requirements.

**Comment by manojsingh101** [comment]
yes, the new function would serve my requirement.

**Comment by markheger** [comment]
toolkit version 1.2.3
