### ISSUE TITLE
Add probabilities to Linear Classification Model output

### ISSUE THREAD

**Issue by mgorbat** [IBMStreams/streamsx.nlp#17]
Current output does not contain probabilities (aka confidence scores) for each class.
Adding probabilities to the output is required to implement thresholds in downstream applications.
Thresholds are used in order to process only predictions with high probability (confidence).

**Comment by joergboe** [comment]
The Linear Classification provides the following output:
The result tuple with one attribute 'classes' which is the list of classifications/predictions and a second attribute 'decisions' which is a list<float64> with the list of decisions.

Where decisions is the output of the LinearSVC decision_function which returns the Confidence scores per (sample, class) combination.

**Comment by joergboe** [comment]
So I think the naming of the output attributes is misleading and should be changed

**Comment by markheger** [comment]
I agree to rename the output attributes

**Comment by hleuschner** [comment]
If users agree, rename is ok. Otherwise, extension of SPLDOC would probably also be sufficient.  We should mention multiple "also know as" like "probability", "confidence", "score" for this parameter.

**Comment by mgorbat** [comment]
I agree to rename the output "decisions": this particular attribute is not yet used in any projects I know of, so it should not affect current implementations, and renaming it will make it more intuitive.
