### ISSUE TITLE
Uimaj Javadocs? 

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.nlp#29]
I have been trying to play with the UIMAJ API for building pear files for the extractors. I was setup nicely using https://uima.apache.org/d/uimaj-current/tutorials_and_users_guides.html#ugr.tug.aae.getting_started, however I am having trouble figuring out how to get a good view of Javadocs. When I go here: https://uima.apache.org/d/uimaj-current/tutorials_and_users_guides.html#ugr.tug.aae.getting_started and click on the Javadoc link, I get a "Not Found" error. Thanks!

**Comment by hleuschner** [comment]
The broken link is https://uima.apache.org/d/uimaj-current/docs/api/index.html
I found the working one: https://uima.apache.org/d/uimaj-current/apidocs/index.html

**Comment by Alex-Cook4** [comment]
Thank you!
