### ISSUE TITLE
RutaText ignores leading whitespace for indexes

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.nlp#30]
If I have a rule that is looking for the word "move", I get the same results from: 
`"   I would like to move  several of my "` as I do for `"I would like to move  several of my "`
resulting in:  {typeDescription="watson.uima.ruta.extractors.Main.Transaction",text="move",begin=16,end=20}

The same test when I'm developing my text analytics handles the whitespace correctly (when I'm purely using UIMA). 

Looks like this is a result of the trim here: https://github.com/IBMStreams/streamsx.nlp/blob/db7e6a2bb2d59c90e35647c99e0713c278ac099c/com.ibm.streamsx.nlp/impl/java/src/com/ibm/streamsx/nlp/RutaText.java#L173

I believe this should be removed, or be optional via an attribute.

**Comment by markheger** [comment]
I would like to add a new optional parameter to be compatible. "trim inputData true" would be the default value.
@Alex-Cook4 Would this be fine for you?

**Comment by Alex-Cook4** [comment]
@markheger That would be great for what I need.

**Comment by markheger** [comment]
solved in release v1.3.0
