### ISSUE TITLE
Do we support .pear files created with Watson Content Analytics? 

### ISSUE THREAD

**Issue by Alex-Cook4** [IBMStreams/streamsx.nlp#34]
Do we support .pear files created with Watson Content Analytics?

**Comment by markheger** [comment]
The UimaText operator is able to process engines compatible with Apache UIMA Core 2.8.1. If Watson Content Anylytics pear file meet this, then they are supported by this toolkit.

**Comment by chanskw** [comment]
I tried it out and I am able to get an exported PEAR file from Watson Content Analytics to work with the uimatext operator
