### ISSUE TITLE
PEAR package extracted in data directory

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.nlp#36]
I tried the UimaText operator.  After running the application, I found my pear file being extracted into the data directory.  While this is ok for on-prem, in the QSE.  I wonder how this will play out in a clustered environment (where data directory may or may not exist), or in the cloud environment, when we can't really write things in the data directory.

Suggest to extract PEAR package somewhere other than the data dir.  The location must be supported in the cloud environment.

**Comment by markheger** [comment]
Data directory can be set to /tmp in a cloud environment:
Following sample job is prepared for Streaming Analytics service:
https://github.com/IBMStreams/streamsx.nlp/tree/master/samples/bluemix/RutaTextCloudSample

**Comment by markheger** [comment]
Operator description updated for Streaming Analytics service in release 1.3.1
