### ISSUE TITLE
Provide operator to parse the CAS output

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.nlp#37]
The Uima operators produces output in CAS output format as a straight rstring.  To process the annotations or data from the CAS output, clients must write parser to parse out the results that are of interest to them.  Is it possible to have operators that can parse the CAS output and produce corresponding tuple types?  So clients do not have to do this work?

**Comment by markheger** [comment]
There is already an output of SPL tuple attributes in addition to the CAS output. See parameter `outputAttributes`.

**Comment by chanskw** [comment]
Is there documentation on what the tuple type should be?
I have trouble figuring out what the output types mean and what tuple tuples are supposed to be.

**Comment by markheger** [comment]
The tool https://github.com/IBMStreams/streamsx.nlp/blob/master/com.ibm.streamsx.nlp/bin/createTypes.pl
helps in generating the types of a PEAR file.
The sample
https://github.com/IBMStreams/streamsx.nlp/tree/master/samples/UimaTextGenerated
demonstrates this.

**Comment by chanskw** [comment]
I have a hard time understanding this documentation:

```
This parameter specifies the name of tuple attributes on the output port for the annotations. This parameter can be specified more than once. The operator assumes that the views from the parameter outputViews are in the same order as the attribute names in this parameter. If this parameter is not specified, the operator expects that the parameter casOut is set. The attribute must a list type.
```

In the case of the output attributes for annotation, what format should the output attribute be?  It mentions that it needs to be a list type, but a list type of what?  is it just an rstring, is it some special schema type?  If it's a special schema type, is it defined globally in the toolkit that people can get to?

**Comment by chanskw** [comment]
Almost feel like we need a tutorial to help people get through this.. :)

**Comment by chanskw** [comment]
I looked at this article:
https://developer.ibm.com/streamsdev/docs/how-to-extract-text-using-the-ibmstreams-extension-text-toolkit-rutatext-operator/

But it does not address these questions and also does not show this type generation either.

**Comment by chanskw** [comment]
Here's some more feedback, and I am unsure if I did this correctly.  I followed your example and added this:

```
(stream<rstring result, list<AnnoSpan> annotations> UimaText_2_out0) as
			UimaText_2 = UimaText(Beacon_1_out0)
		{
			param
				pearFile : "/home/streamsadmin/hostdir/symptomDisease.pear" ;
				casOut : "result" ;
				outputAttributes : "annotations" ;
		}
```

AnnoSpan is defined as:
type AnnoSpan = tuple<rstring text, int32 begin, int32 end, rstring modality, rstring icd10Code> ;

I added modality and icd10Code as extra attributes that I would like to be assigned from the annotations.  These attributes can be found in the XMI that get generated. And those are information information I need to gather for my analytics.  I was expecting that these attributes will get assigned by default if I have it as part of annotations.

When I run this, the annotations list get populated.  But it only has the original word, the start and end of the annotations.  It is missing all the other metadata that was added as part of the annotations.  To get to the modality and icd10Code in my example, I must parse the CAS output.  Am I doing this wrong?  Do you have other suggestions?

Thanks!

**Comment by markheger** [comment]
Have you checked the traces? In case a wrong type is used, you would see error traces "Type mismatch for attribute [...".
Have you generated the type with the `createTypes.pl` script (see comment 4)?

**Comment by chanskw** [comment]
Is there some step-by-step documentation what users are supposed to do?

**Comment by markheger** [comment]
new issue #39 created for easy setup and step-by-step documentation
