### ISSUE TITLE
Running createTypes.pl result in warning

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.nlp#45]
I am unsure what these warning means... are they part of the NLP toolkit?  or are they part of the pear file.. and I should find these files from the annotators that I have exported the pear file from?

warning: failed to load external entity "LWAnnotator1.xml"
warning: failed to load external entity "LWShallowParser3.xml"
warning: failed to load external entity "TypeCleanup5.xml"

**Comment by markheger** [comment]
These files seem to be references by a descriptor file in the PEAR file and can not be loaded since they might be not part of PEAR file.

**Comment by chanskw** [comment]
Here's what I have done to get to this point:
1)  Load the disease and symptoms annotator into Watson Content Analytics Studio
2) Customize the annotator
3)  Export the annotator as a pear file so I can use the NLP toolkit to invoke this annotator.

I will try to figure out how to find these files... but thought it would be helpful if I give you more context.
