### ISSUE TITLE
Relative path for pear file

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.nlp#46]
In trying out the UIMAText operator, I have the following configuration:

(stream<rstring result, list<AnnoSpan> annotations> UimaText_2_out0) as
			UimaText_2 = UimaText(Beacon_1_out0)
		{
			param
				pearFile : "etc/symptomDisease.pear" ;
				casOut : "result" ;
				outputAttributes : "annotations" ;
		}

I have placed the symptomDisease.pear file in the etc directory of the project.  When I run this code, I will get an error saying that ".../etc/etc/symptomDisease.pear" is not found.

This indicates that the relative path handling of the pearFile is relative to the etc directory.  

As a best practise, when a relative path is specified, the path should be relative to the root of the application.

**Comment by markheger** [comment]
You are right that relative from application directory would be a good option, but since operators are used in many projects the path relative from etc should remain for compatibility reason and better documented. It is currently documented in samples only. Operator parameter description needs to be updated.

**Comment by chanskw** [comment]
In addition to pearFile, are there other parameters that handle files?  and are they all relative to etc?  or its own directory?  If there are other parameters, then it may not be just a documentation problem, as we should handle parameters dealing with files consistently.

I understand the requirement to handle compatibility.  Trying to think of an option that will allow us to evolve parameters.

**Comment by markheger** [comment]
Parameter enhancement is tracked by issue #47 
Maybe some operators need to support both for compatibility:
a )relative from applicationDir (should be the recommended new default)
b) search the file relative from etc dir (compatible to current behaviour)

**Comment by chanskw** [comment]
Good stuff... thanks!

**Comment by joergboe** [comment]
Just for clarification of the convention:
- relative paths to configuration files, model files, files with constants roots to application dir
- relative paths to data files, input, output files, custom log fíles, diagnostic-files roots to data dir

Right?

**Comment by chanskw** [comment]
No, all relative paths should be relative to the root of the application directory.  By picking the application root consistently, people do not have to read documentation to figure out how to specify relative paths.

**Comment by chanskw** [comment]
Sorry.. you are right.. :)  I found the guidelines we have previously specified:

Config Files
* Configuration files should be stored in <toolkit>/etc directory.
* Configuration files can to be specified using absolute paths or relative paths.
* If relative paths, config files are relative to the root of the application directory.  i.e. getApplicationDir + path

Data files
* Data files should be stored in "data" directory.
* User must specify data directory at compile time or submission time.
* Data directory is created and managed by customer.  Streams will not create data directory. 
* Relative paths are supported by toolkit operators.  Relative paths will be rooted from the data directory.
