### ISSUE TITLE
Lemmatizer operator memory allocation issue

### ISSUE THREAD

**Issue by vitalizoubov** [IBMStreams/streamsx.nlp#5]
In one of my jobs the nMemoryConsumption metric of the PE, in which the Lemmatizer operator is running, is steadily growing up. Looks like the gposttl Tokenizer function in the Lemmatizer_cpp.cgt module allocates the space that doesn’t get freed.

**Comment by markheger** [comment]
The vendored gposttl source code seems to have several memory leaks. The Tokenizer() and the tag() function are allocating memory that doesn't get released.

**Comment by markheger** [comment]
Fixed in toolkit version 1.2.1
