### ISSUE TITLE
Exception resulted from running symptomAndDisease annotator from content analytics

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.nlp#53]
Seems to be intermittent... need to figure out what causes this exception.

28 Nov 2017 12:41:00.985 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:com.ibm.streams.operator.internal.jni.JNIBridge.process:-1]  - Trying to serialize non-XML 1.0 character: 
28 Nov 2017 12:41:00.987 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - org.xml.sax.SAXParseException: Trying to serialize non-XML 1.0 character: 
28 Nov 2017 12:41:00.987 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.checkForInvalidXmlChars(XMLSerializer.java:374)
28 Nov 2017 12:41:00.987 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - org.apache.uima.util.XMLSerializer$CharacterValidatingContentHandler.startElement(XMLSerializer.java:275)
28 Nov 2017 12:41:00.987 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.startElement(XmiCasSerializer.java:1197)
28 Nov 2017 12:41:00.987 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFsOrLists(XmiCasSerializer.java:711)
28 Nov 2017 12:41:00.988 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFs(XmiCasSerializer.java:697)
28 Nov 2017 12:41:00.988 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.encodeFS(CasSerializerSupport.java:1109)
28 Nov 2017 12:41:00.988 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.encodeQueued(CasSerializerSupport.java:1013)
28 Nov 2017 12:41:00.988 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - org.apache.uima.cas.impl.XmiCasSerializer$XmiDocSerializer.writeFeatureStructures(XmiCasSerializer.java:563)
28 Nov 2017 12:41:00.989 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - org.apache.uima.cas.impl.CasSerializerSupport$CasDocSerializer.serialize(CasSerializerSupport.java:439)
28 Nov 2017 12:41:00.989 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:415)
28 Nov 2017 12:41:00.989 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:366)
28 Nov 2017 12:41:00.989 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - org.apache.uima.cas.impl.XmiCasSerializer.serialize(XmiCasSerializer.java:350)
28 Nov 2017 12:41:00.989 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - com.ibm.streamsx.nlp.AbstractUimaOperator.getXmiString(AbstractUimaOperator.java:485)
28 Nov 2017 12:41:00.989 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - com.ibm.streamsx.nlp.AbstractUimaOperator.createAndSubmitOutputTuple(AbstractUimaOperator.java:720)
28 Nov 2017 12:41:00.990 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - com.ibm.streamsx.nlp.UimaText.handleInputOnPort0(UimaText.java:164)
28 Nov 2017 12:41:00.990 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - com.ibm.streamsx.nlp.AbstractUimaOperator.process(AbstractUimaOperator.java:640)
28 Nov 2017 12:41:00.990 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.processTuple(OperatorAdapter.java:1592)
28 Nov 2017 12:41:00.990 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.runtime.api.OperatorAdapter$1.tuple(OperatorAdapter.java:826)
28 Nov 2017 12:41:00.990 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.runtime.api.OperatorAdapter$1.tuple(OperatorAdapter.java:819)
28 Nov 2017 12:41:00.990 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.ports.SwitchingHandler$Alternate.tuple(SwitchingHandler.java:162)
28 Nov 2017 12:41:00.991 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.network.DeserializingStream.tuple(DeserializingStream.java:76)
28 Nov 2017 12:41:00.991 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.network.DeserializingStream.processRawTuple(DeserializingStream.java:65)
28 Nov 2017 12:41:00.991 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.runtime.api.InputPortsConduit.processRawTuple(InputPortsConduit.java:100)
28 Nov 2017 12:41:00.991 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_javaop M[?:?:0]  - com.ibm.streams.operator.internal.jni.JNIBridge.process(JNIBridge.java:316)
28 Nov 2017 12:41:00.993 [3660] ERROR #splapptrc,J[0],P[0],UimaText_2,spl_function M[JavaOp.cpp:processTuple:1568]  - CDISR5126E: A Java exception occurred at Operator.process() during the JavaOp invocation.
28 Nov 2017 12:41:01.129 [3660

**Comment by markheger** [comment]
Could you please try if CAS serialized as JSON would solve this? You would need to build the toolkit from `feature_cas_json` branch. The new paramter `casJson` needs to be set to `true`.

**Comment by chanskw** [comment]
Figured it out... turns out in the directory that I am reading my data from, there is a hidden file.  The DirectoryScan and FileSource read the file and streamed the content to NLP.

In this case, I think maybe we should consider improving error handling.  When XML / JSON cannot be parsed, we should log the exception and output the data onto the output port, so we can figure out what's wrong without crashing the application.  

I am unsure an error port exists for this operator.

**Comment by markheger** [comment]
Yes, either error port or optional error attribute could help
