### ISSUE TITLE
Support for multithreading

### ISSUE THREAD

**Issue by leongor** [IBMStreams/streamsx.nlp#8]
The following operators define output tuple as an operator member: **Lemmatizer, NgramBasic, TfIdfWeight**.
To allow multiple threads to use it safely a **mutex** or **thread local storage** should be used.
Alternatively if the performance is not an issue, just define it as a local variable.

**Comment by joergboe** [comment]
I propose to make the tuple storage locally in the process method.
The usage of a AutoPortMutex should be considered and depends on the thread safety of the used library functions.

**Comment by joergboe** [comment]
Changes are merged
